#
# Copyright 2025 ProjectASAP contributors
# SPDX-License-Identifier: Apache-2.0
#

aggregations:
  - aggregationId: 2
    aggregationSubType: count
    aggregationType: CountSketch
    aggregationPackage: custom
    parameters:
      rows: 3
      cols: 2048
      trackHH: false # If false, k is not needed
    tumblingWindowSize: 10
