#
# Copyright 2025 ProjectASAP contributors
# SPDX-License-Identifier: Apache-2.0
#

aggregations:
  - aggregationId: 1
    aggregationSubType:
    aggregationType: DataSketchItemsSketch
    aggregationPackage: datasketches
    parameters:
      maxMapSize: 524288
    tumblingWindowSize: 10
